using DynamicData;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Noggog;
using SynAddNpcModelReplacerAsTheNewNpc.Parsers;

namespace SynAddNpcModelReplacerAsTheNewNpc
{
    public class Program
    {
        static Lazy<Settings> _settings = null!;
        internal static Settings Settings { get => _settings.Value; }

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
                .SetTypicalOpen(GameRelease.SkyrimLE, "SynAddNpcModelReplacerAsTheNewNpc.esp")
                .Run(args);
        }

        public class TargetFormKeyData
        {
            public FormKey FormKey;
            public NPCReplacerData? Data;
            public SearchReplacePair? Pair;
            public bool IsChanged;
            public object? Object;
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            General.ShowTargetsInfo();

            AAParse.GetChangedAAList(state);

            ArmorParse.GetChangedSkinArmors(state);

            RaceParse.GetChangedSkinArmors(state);

            AAParse.RelinkRaces(state);

            //NPCParse.GetChangedNPC(state);
            NPCParse.GetChangedNPC2(state);

            //LNPCParse.AddChangedNPC(state);
            LNPCParse.AddChangedNPC2(state);

            //General.CleanNotUsing(state);
        }
    }
}
